version: '2'
services:
  server-express:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerlearning_server-express:1.3.0
    container_name: express-server
    ports:
      - 9000:9000
    env_file:
      - env.list
